name: tmdb_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # modules
  model:
    path: ./modules/model
  core:
    path: ./modules/core
  common_dependencies:
    path: ./modules/common_dependencies
  domain:
    path: ./modules/domain/

  # Movies
  movies:
    path: ./modules/movies/
  ui_common:
    path: ./modules/ui/ui_common
  ui_movies:
    path: ./modules/ui/ui_movies/

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
