name: ui_movies
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  model:
    path: ../../model
  common_dependencies:
    path: ../../common_dependencies

  domain:
    path: ../../domain/
  movies:
    path: ../../movies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
